name: Publish and deploy to staging

on:
  workflow_call:
  workflow_run:
    workflows: ["Check signed commits in PR"]
    types: [requested]
    ## TODO Switch branches when ready to activate
    # branches: [master,release/current]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Workflow run triger
      run: |
        echo "Triggered by workflow_run: ${{ github.event.workflow_run.name }}"

  wf-build-image:
      # if: ${{ github.event.workflow_run.conclusion == 'success' }}
      name: Build and push alpine image
      uses: ./.github/workflows/ci-docker-build.yml
      with:
        image_tag: ${{ github.ref_name == 'master'  && 'rolling' || github.ref_name == 'release/current' && 'prerelease' || github.ref_name }}
        is_client_python_local: true
        is_publish_to_registry: true
      secrets: inherit

  wf-build-fips-image:
      # if: ${{ github.event.workflow_run.conclusion == 'success' }}
      name: Build and push FIPS image
      uses: ./.github/workflows/ci-docker-build.yml
      with:
        image_tag: ${{ github.ref_name == 'master'  && 'rolling' || github.ref_name == 'release/current' && 'prerelease' || github.ref_name }}
        is_client_python_local: true
        is_publish_to_registry: true
        is_fips: true
      secrets: inherit

  wf-publish-package:
      # if: ${{ github.event.workflow_run.conclusion == 'success' }}
      name: Publish OpenCTI platform packages
      uses: ./.github/workflows/cd-publish-package.yml
      with:
        is_client_python_local: true
