name: OpenCTI CI
on:
  workflow_dispatch:

jobs:
  Runner-informtion:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set-dev
    steps:
    - name: Display Runner Information
      run: |
          echo "Runner Name: $RUNNER_NAME"
          echo "Runner OS: $RUNNER_OS \t Runner Arch: $RUNNER_ARCH"
          echo "Workflow: ${{ github.workflow }} \t Run ID: ${{ github.run_id }} \t Run Number: ${{ github.run_number }}"
