name: OpenCTI CI self hosted
on:
  workflow_dispatch:
#  push:
#  pull_request:

jobs:
  OpenCTI-CI:
    runs-on: arc-runner-set-dev
    container: ubuntu:latest
    steps:
    - name: Display Runner Information
      continue-on-error: true
      run: |
          set -ex
          echo "Runner Name: $RUNNER_NAME \n Runner OS: $RUNNER_OS \n Runner Arch: $RUNNER_ARCH"
          echo "Workflow: ${{ github.workflow }} \t Run ID: ${{ github.run_id }} \t Run Number: ${{ github.run_number }}"
          echo "Workspace  GITHUB_WORKSPACE =  ${GITHUB_WORKSPACE}  \t   github.workspace= ${{ github.workspace }} \t  pwd $(pwd) "
          env

    - name: OpenCTI checkout
      uses: actions/checkout@v4


    - name: Collect Workflow Telemetry
      uses: catchpoint/workflow-telemetry-action@v2

    - name: Start api test
      run: |
        docker run --network runner-docker-network \
          --name api-tests \
          -p 4010:4100 \
          -v ${{ github.workspace }}:/home/workspace \
          -e APP__BASE_URL=http://api-tests:4010/ \
          -e APP__ADMIN__PASSWORD=admin \
          -e APP__CHILD_LOCKING_PROCESS__ENABLED=false \
          -e APP__ENTERPRISE_EDITION_LICENSE="${{ secrets.EE_LICENSE }}" \
          -e APP__SYNC_RAW_START_REMOTE_URI=http://opencti-raw-start:4100/graphql \
          -e APP__SYNC_LIVE_START_REMOTE_URI=http://opencti-live-start:4100/graphql \
          -e APP__SYNC_DIRECT_START_REMOTE_URI=http://opencti-direct-start:4100/graphql \
          -e APP__SYNC_RESTORE_START_REMOTE_URI=http://opencti-restore-start:4100/graphql \
          -e APP__ADMIN__TOKEN=bfa014e0-e02e-4aa6-a42b-603b19dcf159 \
          -e REDIS__HOSTNAME=redis \
          -e ELASTICSEARCH__URL=http://elasticsearch:9200 \
          -e MINIO__ENDPOINT=minio \
          -e RABBITMQ__HOSTNAME=rabbitmq \
          -e EXPIRATION_SCHEDULER__ENABLED=false \
          -e SUBSCRIPTION_SCHEDULER__ENABLED=false \
          -e SMTP__ENABLED=false \
          -e PYTHONUNBUFFERED=1  \
          nikolaik/python-nodejs:python3.11-nodejs22-alpine \
          sh -c 'set -ex;
            echo -e "\n\n *********\n ********* Start OpenCTI API test";
            echo "$(ls /root/.yarn/berry/cache/ 2> /dev/null | wc -l || echo 0) packages in Yarn global cache";
            apk add build-base git libffi-dev cargo;
            cd /home/workspace
            git clone https://github.com/OpenCTI-Platform/connectors.git opencti-connectors
            git clone https://github.com/OpenCTI-Platform/client-python.git
            cd /home/workspace/opencti-platform/opencti-graphql
            npm install -g corepack
            cp /home/workspace/opencti-platform/.yarnrc.yml .
            yarn install
            yarn build
            yarn check-ts
            yarn lint
            NODE_OPTIONS=--max_old_space_size=8192 yarn test:ci-integration
        '

