name: OpenCTI CI
on:
  workflow_dispatch:
  push:

jobs:
  OpenCTI-CI:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set-dev
    steps:
    - name: Display Runner Information
      run: |
          echo "Runner Name: $RUNNER_NAME"
          echo "Runner OS: $RUNNER_OS \t Runner Arch: $RUNNER_ARCH"
          echo "Workflow: ${{ github.workflow }} \t Run ID: ${{ github.run_id }} \t Run Number: ${{ github.run_number }}"

    services:
      redis:
        image: redis:8.0.0
        ports:
          - 6379:6379
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.18.2
        ports:
          - 9200:9200
        options: --health-cmd="curl http://localhost:9200/_cluster/health"
